### ISSUE TITLE
Missing `SAH` function

### ISSUE THREAD

**Issue by moberst** [matthieukomorowski/AI_Clinician#4]
On line 476 in `AIClinician_sepsis3_def_160219.m`, the SAH function is undefined.  It does not appear to be defined anywhere else in the repo

https://github.com/matthieukomorowski/AI_Clinician/blob/1a57264a851499f2cf442676e93ab8118d16ae2b/AIClinician_sepsis3_def_160219.m#L476

This causes the following error when the script is run
```
Undefined function or variable 'SAH'.

Error in AIClinician_sepsis3_def_160219 (line 477)
reformatsah=SAH(reformat,sample_and_hold);  % do SAH first to handle this task
```

**Comment by moberst** [comment]
@matthieukomorowski is there a file missing from the repo, perhaps, which defines this function?

**Comment by paulrich1234** [comment]
@moberst  hello have you solved the problems and could you tell me how if you had solved the problem.thank u

**Comment by moberst** [comment]
@matthieukomorowski uploaded the file this morning, going to close this issue
